[server]
heartbeat_interval_ms = 1000
connection_pool_size = 16

[batch]

[streaming]
checkpoint_interval_ms = 250
in_flight_barrier_nums = 40
worker_node_parallelism = 4

[storage]
shared_buffer_capacity_mb = 4096
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.01
data_directory = "hummock_001"
block_cache_capacity_mb = 4096
meta_cache_capacity_mb = 1024
compactor_memory_limit_mb = 5120

[storage.file_cache]
capacity_mb = 1024
total_buffer_capacity_mb = 128
cache_file_fallocate_unit_mb = 512
cache_meta_fallocate_unit_mb = 16

[streaming.developer]
enable_executor_row_count = false
